<a href="https://colab.research.google.com/github/golfn123/CE888Project/blob/main/labs/lab6/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np


In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv',header= None)
df

0      1      2      3      4     5      6     7     8      9    ...  \
0       74  -7.82   8.79  -9.66  -8.16 -7.52  -8.50 -9.85  4.17  -8.98  ...   
1      100   4.08  -0.29   6.36   4.37 -2.38  -9.66 -0.73 -5.34   8.88  ...   
2       49  99.00  99.00  99.00  99.00  9.03   9.27  9.03  9.27  99.00  ...   
3       48  99.00   8.35  99.00  99.00  1.80   8.16 -2.82  6.21  99.00  ...   
4       91   8.50   4.61  -4.17  -5.39  1.36   1.60  7.04  4.61  -0.44  ...   
...    ...    ...    ...    ...    ...   ...    ...   ...   ...    ...  ...   
24978  100   0.44   7.43   9.08   2.33  3.20   6.75 -8.79 -0.53  -8.74  ...   
24979   91   9.13  -8.16   8.59   9.08  0.87  -8.93 -3.50  5.78  -8.11  ...   
24980   39  99.00  99.00  99.00  99.00 -7.77  99.00  6.70 -6.75  99.00  ...   
24981   37  99.00  99.00  99.00  99.00 -9.71  99.00  4.56 -8.30  99.00  ...   
24982   72   2.43   2.67  -3.98   4.27 -2.28   7.33  2.33  4.56   6.75  ...   

         91     92     93     94     95     96     97     98     99     100  
0       2.82  99.00  99.00  99.00  99.00  99.00  -5.63  99.00  99.00  99.00  
1       2.82  -4.95  -0.29   7.86  -0.19  -2.14   3.06   0.34  -4.32   1.07  
2      99.00  99.00  99.00   9.08  99.00  99.00  99.00  99.00  99.00  99.00  
3      99.00  99.00  99.00   0.53  99.00  99.00  99.00  99.00  99.00  99.00  
4       5.19   5.58   4.27   5.19   5.73   1.55   3.11   6.55   1.80   1.60  
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
24978   8.83  -1.21   9.22  -6.70   8.45   9.03   6.55   8.69   8.79   7.43  
24979  -1.17  -5.73  -1.46   0.24   9.22  -8.20  -7.23  -8.59   9.13   8.45  
24980  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  
24981  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  
24982  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  

[24983 rows x 101 columns]

In [3]:
df.replace(99, np.NaN,inplace= True)
df

0     1     2     3     4     5     6     7     8     9    ...   91   \
0       74.0 -7.82  8.79 -9.66 -8.16 -7.52 -8.50 -9.85  4.17 -8.98  ...  2.82   
1      100.0  4.08 -0.29  6.36  4.37 -2.38 -9.66 -0.73 -5.34  8.88  ...  2.82   
2       49.0   NaN   NaN   NaN   NaN  9.03  9.27  9.03  9.27   NaN  ...   NaN   
3       48.0   NaN  8.35   NaN   NaN  1.80  8.16 -2.82  6.21   NaN  ...   NaN   
4       91.0  8.50  4.61 -4.17 -5.39  1.36  1.60  7.04  4.61 -0.44  ...  5.19   
...      ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
24978  100.0  0.44  7.43  9.08  2.33  3.20  6.75 -8.79 -0.53 -8.74  ...  8.83   
24979   91.0  9.13 -8.16  8.59  9.08  0.87 -8.93 -3.50  5.78 -8.11  ... -1.17   
24980   39.0   NaN   NaN   NaN   NaN -7.77   NaN  6.70 -6.75   NaN  ...   NaN   
24981   37.0   NaN   NaN   NaN   NaN -9.71   NaN  4.56 -8.30   NaN  ...   NaN   
24982   72.0  2.43  2.67 -3.98  4.27 -2.28  7.33  2.33  4.56  6.75  ...   NaN   

        92    93    94    95    96    97    98    99    100  
0       NaN   NaN   NaN   NaN   NaN -5.63   NaN   NaN   NaN  
1     -4.95 -0.29  7.86 -0.19 -2.14  3.06  0.34 -4.32  1.07  
2       NaN   NaN  9.08   NaN   NaN   NaN   NaN   NaN   NaN  
3       NaN   NaN  0.53   NaN   NaN   NaN   NaN   NaN   NaN  
4      5.58  4.27  5.19  5.73  1.55  3.11  6.55  1.80  1.60  
...     ...   ...   ...   ...   ...   ...   ...   ...   ...  
24978 -1.21  9.22 -6.70  8.45  9.03  6.55  8.69  8.79  7.43  
24979 -5.73 -1.46  0.24  9.22 -8.20 -7.23 -8.59  9.13  8.45  
24980   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
24981   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
24982   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[24983 rows x 101 columns]

In [4]:
df=df.drop([0],axis=1)
df

1     2     3     4     5     6     7     8     9     10   ...   91   \
0     -7.82  8.79 -9.66 -8.16 -7.52 -8.50 -9.85  4.17 -8.98 -4.76  ...  2.82   
1      4.08 -0.29  6.36  4.37 -2.38 -9.66 -0.73 -5.34  8.88  9.22  ...  2.82   
2       NaN   NaN   NaN   NaN  9.03  9.27  9.03  9.27   NaN   NaN  ...   NaN   
3       NaN  8.35   NaN   NaN  1.80  8.16 -2.82  6.21   NaN  1.84  ...   NaN   
4      8.50  4.61 -4.17 -5.39  1.36  1.60  7.04  4.61 -0.44  5.73  ...  5.19   
...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
24978  0.44  7.43  9.08  2.33  3.20  6.75 -8.79 -0.53 -8.74  7.23  ...  8.83   
24979  9.13 -8.16  8.59  9.08  0.87 -8.93 -3.50  5.78 -8.11  4.90  ... -1.17   
24980   NaN   NaN   NaN   NaN -7.77   NaN  6.70 -6.75   NaN   NaN  ...   NaN   
24981   NaN   NaN   NaN   NaN -9.71   NaN  4.56 -8.30   NaN   NaN  ...   NaN   
24982  2.43  2.67 -3.98  4.27 -2.28  7.33  2.33  4.56  6.75  4.61  ...   NaN   

        92    93    94    95    96    97    98    99    100  
0       NaN   NaN   NaN   NaN   NaN -5.63   NaN   NaN   NaN  
1     -4.95 -0.29  7.86 -0.19 -2.14  3.06  0.34 -4.32  1.07  
2       NaN   NaN  9.08   NaN   NaN   NaN   NaN   NaN   NaN  
3       NaN   NaN  0.53   NaN   NaN   NaN   NaN   NaN   NaN  
4      5.58  4.27  5.19  5.73  1.55  3.11  6.55  1.80  1.60  
...     ...   ...   ...   ...   ...   ...   ...   ...   ...  
24978 -1.21  9.22 -6.70  8.45  9.03  6.55  8.69  8.79  7.43  
24979 -5.73 -1.46  0.24  9.22 -8.20 -7.23 -8.59  9.13  8.45  
24980   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
24981   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
24982   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[24983 rows x 100 columns]

In [5]:
df_mean = df.mean()
df_mean.sort_values()

58   -3.833880
16   -3.104818
44   -2.111891
57   -1.990664
13   -1.762882
        ...   
32    3.155988
27    3.189821
36    3.312500
89    3.574720
50    3.665085
Length: 100, dtype: float64

In [6]:
#find lowest rating jokes
summary = []
for i in df.columns:
  #min = np.minimum(df[i])
  summary.append(np.mean(df[i]))

In [10]:
min = np.min(summary)
min

-3.8338796373689923

In [8]:
df.shape[0]

24983

In [9]:
avg_rate= -77542.83/24983
print(avg_rate)

-3.1038238001841254


In [12]:
df.iloc[6549, 37]

-9.22

In [ ]:
arr= df.values
arr

array([[-7.82,  8.79, -9.66, ...,   nan,   nan,   nan],
       [ 4.08, -0.29,  6.36, ...,  0.34, -4.32,  1.07],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       ...,
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [ 2.43,  2.67, -3.98, ...,   nan,   nan,   nan]])

In [ ]:

def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with NaN's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr != np.NaN)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

replace(arr)

(array([[-7.82,  8.79, -9.66, ...,   nan,   nan,   nan],
        [ 4.08, -0.29, 99.  , ...,  0.34, -4.32,  1.07],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        ...,
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        [ 2.43,  2.67, -3.98, ..., 99.  ,   nan,   nan]]),
 (array([22557, 24765, 18848, ..., 12857, 22016, 16790]),
  array([14, 68,  3, ..., 12, 23, 59])))

In [67]:
#load movie dataset
movie_df= pd.read_excel('movies_latent_factors.xlsx')
movie_df

Movie ID                                              Title   Factor1  \
0         11          Star Wars: Episode IV - A New Hope (1977) -1.521848   
1         12                                Finding Nemo (2003) -0.342185   
2         13                                Forrest Gump (1994) -2.240888   
3         14                             American Beauty (1999) -0.634531   
4         22  Pirates of the Caribbean: The Curse of the Bla...  0.517348   
..       ...                                                ...       ...   
95      9806                             The Incredibles (2004)  0.159967   
96     10020                        Beauty and the Beast (1991)  1.286288   
97     36657                                       X-Men (2000)  0.811901   
98     36658                            X2: X-Men United (2003)  1.161006   
99     36955                                   True Lies (1994)  1.734008   

     Factor2   Factor3   Factor4   Factor5   Factor6   Factor7   Factor8  \
0  -1.038507  2.027269  0.247933 -0.594548  2.513260 -1.848910  0.476710   
1  -0.296586 -0.385962  2.443297 -1.097015 -0.619465  0.572887  0.329516   
2  -0.438815 -2.275177  0.614548  0.904469  0.711919 -0.420876  1.302036   
3   2.186059 -0.066681  0.086197  0.517558 -0.185319 -0.412352  0.063841   
4  -1.456763  0.369161  0.073903 -0.098332 -0.594722  0.828888  0.033626   
..       ...       ...       ...       ...       ...       ...       ...   
95 -0.051123  0.311183  1.841867 -1.952736 -0.836041  0.639252 -0.413082   
96  0.004957 -0.157640  2.579640 -0.042687 -0.256582 -0.007971  0.458163   
97 -0.893280  0.668953 -0.885074 -1.070468 -0.973154 -0.037449 -0.925609   
98 -0.715613  0.712633 -0.688808 -0.717785 -1.007047 -0.267268 -0.802322   
99  0.265436 -0.003391 -0.491754 -0.322739  0.850165 -0.150377 -0.075895   

     Factor9  Factor10  Factor11  Factor12  Factor13  Factor14  Factor15  
0  -0.224146 -0.760681 -0.973915  0.862379  0.403861  1.129616 -0.248806  
1  -0.712228  0.323554 -0.561948 -0.142405 -0.564415  0.506876  1.274993  
2  -0.868418 -0.160122  0.633667  0.133138 -0.330276 -2.209004 -0.419092  
3   0.075937 -0.577682  0.526803 -1.465557 -0.819682  0.549010 -0.681191  
4  -0.707414  0.717877  1.394326 -0.786986  1.429191  0.855746 -2.292566  
..       ...       ...       ...       ...       ...       ...       ...  
95 -0.310868  0.448225 -0.846044 -0.158192 -0.649164  0.045580  1.017861  
96  0.091394  0.323339 -0.862833 -0.508185  0.994535  0.868700 -0.487076  
97 -0.122112 -0.328822 -0.163103 -0.307299  0.642105 -1.355542  0.067790  
98 -0.249239 -0.540419 -0.291422 -0.240216  0.290714 -1.217250 -0.288130  
99  1.373386  0.934767  0.489299 -0.062678  0.333703 -0.223382 -0.022599  

[100 rows x 17 columns]

In [15]:
movie_df.loc[movie_df['Movie ID'] == 85]

Movie ID                                              Title   Factor1  \
9        85  Raiders of the Lost Ark (Indiana Jones and the... -1.241724   

   Factor2   Factor3   Factor4   Factor5   Factor6   Factor7   Factor8  \
9  0.02113  0.489161  0.424584 -1.262253  1.190654 -0.606434  0.305721   

    Factor9  Factor10  Factor11  Factor12  Factor13  Factor14  Factor15  
9  1.438862  0.402682  0.438831  0.784948 -0.874375 -0.399984 -0.197686

In [ ]:
movie_df.loc[movie_df['Movie ID'] == 955]

Movie ID                          Title  ...  Factor14  Factor15
72       955  Mission: Impossible II (2000)  ...  1.547867 -0.997373

[1 rows x 17 columns]

In [18]:
min=movie_df['Factor12'].min()
min

-2.568581806405218

In [20]:
movie_df.loc[movie_df['Factor12']== min]

Movie ID           Title   Factor1   Factor2   Factor3   Factor4  \
47       597  Titanic (1997)  1.567865 -1.516952 -2.523378  1.204485   

     Factor5   Factor6   Factor7   Factor8   Factor9  Factor10  Factor11  \
47  1.729541 -0.088941  0.102822  1.747792  1.816958 -2.986807 -0.589441   

    Factor12  Factor13  Factor14  Factor15  
47 -2.568582  0.370387  2.215933  0.456127

In [22]:
def sgd(iterations):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    mse_history = []
    for iteration in range(iterations):
        error = []
        for user_id in latent_user_features.shape[0]:
          for item_id in latent_item_features.shape[0]:
            ratings = user_ratings[user_id,item_id]
            if not np.isnan(ratings) and  ratings !=99:
              err = (train(user_id, item_id, ratings))
              error.append(err) 
        
        ### YOUR CODE (inner loop) HERE
        
        
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 10) == 0:
            print('Iteration %d/%d:    MSE=%.3f' % (iteration, iterations, mse))
            mse_history.append(mse)
    return mse_history

In [139]:
Movies_user= pd.read_excel('movies_latent_factors.xlsx', 'Users')
Movies_user

User   Factor1   Factor2   Factor3   Factor4   Factor5   Factor6  \
0   4768 -0.204024  0.161079 -0.090447  0.138495 -0.162934  0.163894   
1    156 -0.189652 -0.178979 -0.091490 -0.000823 -0.032646  0.177209   
2   5323 -0.115308 -0.090886 -0.053129  0.018472 -0.068081 -0.004828   
3    174 -0.227462 -0.272532 -0.017231  0.054324  0.214755 -0.072639   
4   4529 -0.014616 -0.102218 -0.107935  0.155784 -0.123362 -0.118228   
5    783 -0.020301 -0.031919 -0.036955  0.033690  0.000174 -0.003178   
6   3878 -0.091462  0.215879 -0.180453  0.085408 -0.321094  0.227947   
7    768  0.000819 -0.009229 -0.019228  0.002703  0.012869  0.006655   
8   4469 -0.030528 -0.011537 -0.042822 -0.014378  0.031338  0.012297   
9   1882 -0.083093 -0.029160  0.013748  0.022716 -0.062732 -0.080670   
10  4997 -0.185443 -0.276496 -0.781275 -0.240506  0.029611 -0.271814   
11  2067 -0.083242  0.181171 -0.344267 -0.019713 -0.243199  0.039220   
12  3806 -0.042344 -0.040755 -0.055720 -0.073726  0.018203  0.091940   
13  2848 -0.113283 -0.098942 -0.040393  0.042180 -0.041068 -0.039568   
14  4433 -0.298760 -0.290228 -0.160120  0.156277 -0.055364 -0.434205   
15  3519 -0.068454  0.020090  0.039336  0.002958 -0.018140  0.006501   
16  5338 -0.061259  0.014661  0.011412  0.001727  0.064996 -0.078448   
17  3947 -0.022340 -0.115285 -0.136980  0.038593 -0.003029  0.071770   
18  4373 -0.136550 -0.089406 -0.235399  0.120585 -0.168168  0.129990   
19  2092 -0.121763  0.011065 -0.037121  0.032568  0.017570  0.095802   
20   525 -0.040290  0.014383 -0.098967 -0.018957  0.012388  0.035546   
21  4327  0.008227  0.073899 -0.323967  0.131203 -0.320862  0.054997   
22  3048 -0.320315  0.078290 -0.083182 -0.221577 -0.078184 -0.145306   
23  2665 -0.076167 -0.006064 -0.001902 -0.053641  0.021751  0.048207   
24  4940 -0.113099  0.047643 -0.053024  0.024834  0.010643 -0.012051   

     Factor7   Factor8   Factor9  Factor10  Factor11  Factor12  Factor13  \
0   0.051502 -0.088582  0.126829  0.065967  0.085008  0.355404  0.007108   
1  -0.098123 -0.068283 -0.011575  0.120866 -0.009931 -0.048606  0.045916   
2   0.113005  0.102107  0.034758  0.000693 -0.073712 -0.019460  0.108372   
3  -0.033122 -0.086508 -0.131479  0.180403  0.095890 -0.082396  0.036767   
4  -0.013549 -0.050622  0.058698 -0.159600 -0.142382 -0.132836 -0.039897   
5   0.054474  0.045424 -0.053308  0.003437 -0.041750  0.059725 -0.021647   
6   0.053767  0.038017  0.097141 -0.139872  0.029253  0.214467  0.189250   
7   0.007687  0.018747  0.014705 -0.009256 -0.010116 -0.010051 -0.002108   
8  -0.000038 -0.010264 -0.006781 -0.019950 -0.014435  0.010926  0.024400   
9  -0.019723  0.013253 -0.091305 -0.090687  0.030638 -0.113364 -0.021325   
10 -0.056266 -0.111825 -0.290910 -0.255087 -0.098079  0.103116 -0.100563   
11 -0.092086  0.114808 -0.036472  0.042386 -0.186812 -0.127038  0.176661   
12  0.123959 -0.157403 -0.020388  0.082493  0.223057 -0.040915 -0.130308   
13  0.018291 -0.191254  0.218912  0.017262 -0.087468  0.036894  0.067105   
14 -0.089259  0.252211 -0.107413 -0.088591  0.121157  0.071371 -0.415598   
15 -0.108526  0.025045  0.056334 -0.031291 -0.035533  0.005171  0.005546   
16  0.059510  0.017402 -0.040234 -0.073409 -0.016323  0.031774 -0.062413   
17 -0.146675 -0.285724 -0.044472 -0.054032  0.064019 -0.045329 -0.111919   
18 -0.035084 -0.324028  0.087531  0.045290  0.207850 -0.028972 -0.175184   
19  0.120238 -0.048410  0.008829  0.121778  0.093783  0.044754 -0.003087   
20  0.000903  0.012835 -0.021080  0.018742 -0.050483 -0.025394  0.034079   
21  0.060751  0.162314  0.044612 -0.232241  0.094986 -0.106570 -0.051692   
22 -0.020166  0.124409 -0.063425  0.004726  0.009683  0.028016 -0.018100   
23 -0.083980  0.146907 -0.057422  0.006085  0.063240  0.086562 -0.132328   
24 -0.049150  0.006252  0.020429  0.004349  0.028372  0.010227 -0.008233   

    Factor14  Factor15  
0  -0.118663 -0.039125  
1   0.113671  0.179873  
2   0.054471 -0.109552  
3  -0.165438  0.050692  
4   0.129063  0.102669  
5   

In [27]:
#from sklearn.svm import SVC

In [55]:
'''
Movies_user["key"] = 0
Movies_user["user_id"] = range(Movies_user.shape[0])   #user_id
movie_df["key"] = 0
movie_df['item_id'] = range(movie_df.shape[0])   #item_id

In [140]:
Movies_user

User   Factor1   Factor2   Factor3   Factor4   Factor5   Factor6  \
0   4768 -0.204024  0.161079 -0.090447  0.138495 -0.162934  0.163894   
1    156 -0.189652 -0.178979 -0.091490 -0.000823 -0.032646  0.177209   
2   5323 -0.115308 -0.090886 -0.053129  0.018472 -0.068081 -0.004828   
3    174 -0.227462 -0.272532 -0.017231  0.054324  0.214755 -0.072639   
4   4529 -0.014616 -0.102218 -0.107935  0.155784 -0.123362 -0.118228   
5    783 -0.020301 -0.031919 -0.036955  0.033690  0.000174 -0.003178   
6   3878 -0.091462  0.215879 -0.180453  0.085408 -0.321094  0.227947   
7    768  0.000819 -0.009229 -0.019228  0.002703  0.012869  0.006655   
8   4469 -0.030528 -0.011537 -0.042822 -0.014378  0.031338  0.012297   
9   1882 -0.083093 -0.029160  0.013748  0.022716 -0.062732 -0.080670   
10  4997 -0.185443 -0.276496 -0.781275 -0.240506  0.029611 -0.271814   
11  2067 -0.083242  0.181171 -0.344267 -0.019713 -0.243199  0.039220   
12  3806 -0.042344 -0.040755 -0.055720 -0.073726  0.018203  0.091940   
13  2848 -0.113283 -0.098942 -0.040393  0.042180 -0.041068 -0.039568   
14  4433 -0.298760 -0.290228 -0.160120  0.156277 -0.055364 -0.434205   
15  3519 -0.068454  0.020090  0.039336  0.002958 -0.018140  0.006501   
16  5338 -0.061259  0.014661  0.011412  0.001727  0.064996 -0.078448   
17  3947 -0.022340 -0.115285 -0.136980  0.038593 -0.003029  0.071770   
18  4373 -0.136550 -0.089406 -0.235399  0.120585 -0.168168  0.129990   
19  2092 -0.121763  0.011065 -0.037121  0.032568  0.017570  0.095802   
20   525 -0.040290  0.014383 -0.098967 -0.018957  0.012388  0.035546   
21  4327  0.008227  0.073899 -0.323967  0.131203 -0.320862  0.054997   
22  3048 -0.320315  0.078290 -0.083182 -0.221577 -0.078184 -0.145306   
23  2665 -0.076167 -0.006064 -0.001902 -0.053641  0.021751  0.048207   
24  4940 -0.113099  0.047643 -0.053024  0.024834  0.010643 -0.012051   

     Factor7   Factor8   Factor9  Factor10  Factor11  Factor12  Factor13  \
0   0.051502 -0.088582  0.126829  0.065967  0.085008  0.355404  0.007108   
1  -0.098123 -0.068283 -0.011575  0.120866 -0.009931 -0.048606  0.045916   
2   0.113005  0.102107  0.034758  0.000693 -0.073712 -0.019460  0.108372   
3  -0.033122 -0.086508 -0.131479  0.180403  0.095890 -0.082396  0.036767   
4  -0.013549 -0.050622  0.058698 -0.159600 -0.142382 -0.132836 -0.039897   
5   0.054474  0.045424 -0.053308  0.003437 -0.041750  0.059725 -0.021647   
6   0.053767  0.038017  0.097141 -0.139872  0.029253  0.214467  0.189250   
7   0.007687  0.018747  0.014705 -0.009256 -0.010116 -0.010051 -0.002108   
8  -0.000038 -0.010264 -0.006781 -0.019950 -0.014435  0.010926  0.024400   
9  -0.019723  0.013253 -0.091305 -0.090687  0.030638 -0.113364 -0.021325   
10 -0.056266 -0.111825 -0.290910 -0.255087 -0.098079  0.103116 -0.100563   
11 -0.092086  0.114808 -0.036472  0.042386 -0.186812 -0.127038  0.176661   
12  0.123959 -0.157403 -0.020388  0.082493  0.223057 -0.040915 -0.130308   
13  0.018291 -0.191254  0.218912  0.017262 -0.087468  0.036894  0.067105   
14 -0.089259  0.252211 -0.107413 -0.088591  0.121157  0.071371 -0.415598   
15 -0.108526  0.025045  0.056334 -0.031291 -0.035533  0.005171  0.005546   
16  0.059510  0.017402 -0.040234 -0.073409 -0.016323  0.031774 -0.062413   
17 -0.146675 -0.285724 -0.044472 -0.054032  0.064019 -0.045329 -0.111919   
18 -0.035084 -0.324028  0.087531  0.045290  0.207850 -0.028972 -0.175184   
19  0.120238 -0.048410  0.008829  0.121778  0.093783  0.044754 -0.003087   
20  0.000903  0.012835 -0.021080  0.018742 -0.050483 -0.025394  0.034079   
21  0.060751  0.162314  0.044612 -0.232241  0.094986 -0.106570 -0.051692   
22 -0.020166  0.124409 -0.063425  0.004726  0.009683  0.028016 -0.018100   
23 -0.083980  0.146907 -0.057422  0.006085  0.063240  0.086562 -0.132328   
24 -0.049150  0.006252  0.020429  0.004349  0.028372  0.010227 -0.008233   

    Factor14  Factor15  
0  -0.118663 -0.039125  
1   0.113671  0.179873  
2   0.054471 -0.109552  
3  -0.165438  0.050692  
4   0.129063  0.102669  
5   

In [141]:
movie_df

Movie ID                                              Title   Factor1  \
0         11          Star Wars: Episode IV - A New Hope (1977) -1.521848   
1         12                                Finding Nemo (2003) -0.342185   
2         13                                Forrest Gump (1994) -2.240888   
3         14                             American Beauty (1999) -0.634531   
4         22  Pirates of the Caribbean: The Curse of the Bla...  0.517348   
..       ...                                                ...       ...   
95      9806                             The Incredibles (2004)  0.159967   
96     10020                        Beauty and the Beast (1991)  1.286288   
97     36657                                       X-Men (2000)  0.811901   
98     36658                            X2: X-Men United (2003)  1.161006   
99     36955                                   True Lies (1994)  1.734008   

     Factor2   Factor3   Factor4   Factor5   Factor6   Factor7   Factor8  \
0  -1.038507  2.027269  0.247933 -0.594548  2.513260 -1.848910  0.476710   
1  -0.296586 -0.385962  2.443297 -1.097015 -0.619465  0.572887  0.329516   
2  -0.438815 -2.275177  0.614548  0.904469  0.711919 -0.420876  1.302036   
3   2.186059 -0.066681  0.086197  0.517558 -0.185319 -0.412352  0.063841   
4  -1.456763  0.369161  0.073903 -0.098332 -0.594722  0.828888  0.033626   
..       ...       ...       ...       ...       ...       ...       ...   
95 -0.051123  0.311183  1.841867 -1.952736 -0.836041  0.639252 -0.413082   
96  0.004957 -0.157640  2.579640 -0.042687 -0.256582 -0.007971  0.458163   
97 -0.893280  0.668953 -0.885074 -1.070468 -0.973154 -0.037449 -0.925609   
98 -0.715613  0.712633 -0.688808 -0.717785 -1.007047 -0.267268 -0.802322   
99  0.265436 -0.003391 -0.491754 -0.322739  0.850165 -0.150377 -0.075895   

     Factor9  Factor10  Factor11  Factor12  Factor13  Factor14  Factor15  
0  -0.224146 -0.760681 -0.973915  0.862379  0.403861  1.129616 -0.248806  
1  -0.712228  0.323554 -0.561948 -0.142405 -0.564415  0.506876  1.274993  
2  -0.868418 -0.160122  0.633667  0.133138 -0.330276 -2.209004 -0.419092  
3   0.075937 -0.577682  0.526803 -1.465557 -0.819682  0.549010 -0.681191  
4  -0.707414  0.717877  1.394326 -0.786986  1.429191  0.855746 -2.292566  
..       ...       ...       ...       ...       ...       ...       ...  
95 -0.310868  0.448225 -0.846044 -0.158192 -0.649164  0.045580  1.017861  
96  0.091394  0.323339 -0.862833 -0.508185  0.994535  0.868700 -0.487076  
97 -0.122112 -0.328822 -0.163103 -0.307299  0.642105 -1.355542  0.067790  
98 -0.249239 -0.540419 -0.291422 -0.240216  0.290714 -1.217250 -0.288130  
99  1.373386  0.934767  0.489299 -0.062678  0.333703 -0.223382 -0.022599  

[100 rows x 17 columns]

In [61]:
'''
merged_df = pd.merge(Movies_user, movie_df, left_index=True, on="key")
merged_df.drop(labels='key', axis=1, inplace=True)  # drop the "key" column


MergeError: ignored

In [ ]:
'''
clf  = SVC()

X_tr, y_tr = train.iloc[:, :-1].values, train.iloc[:, -1].values  # separate into X and y

clf.fit(X_tr, y_tr)


In [165]:
#['Factor1','Factor2','Factor3','Factor4','Factor5','Factor6','Factor7','Factor8','Factor9','Factor10','Factor11','Factor12','Factor13','Factor14','Factor15']

def predict_rating(user_id, item_id):
    """
    Predict a rating given a user_id and an item_id.
    """

    user_preference = Movies_user.loc[Movies_user['User'] == user_id]
    item_preference = movie_df.loc[movie_df['Movie ID'] == item_id]
    users = user_preference.drop(['User'], axis=1)
    items = item_preference.drop(['Movie ID','Title'], axis=1)
    users = np.array(users)
    items = np.array(items)
    ans= users.dot(items.T)
    #user_features_weights = Movies_user[['Factor1','Factor2','Factor3','Factor4','Factor5','Factor6','Factor7','Factor8','Factor9','Factor10','Factor11','Factor12','Factor13','Factor14','Factor15']]
    #item_features_weights = movie_df[['Factor1','Factor2','Factor3','Factor4','Factor5','Factor6','Factor7','Factor8','Factor9','Factor10','Factor11','Factor12','Factor13','Factor14','Factor15']].T
    #print(user_preference.dot(item_preference) + user_score + item_score)
    #print(users.shape)
    #print(items.shape)
    return ans
    #return user_preference.dot(item_preference.T)

In [148]:
#
movie_df.loc[movie_df['Movie ID'] == 77]

Movie ID           Title  Factor1   Factor2   Factor3   Factor4  Factor5  \
8        77  Memento (2000) -1.44373  1.466671 -0.121894 -0.237937 -0.30101   

    Factor6   Factor7   Factor8   Factor9  Factor10  Factor11  Factor12  \
8 -0.650094 -0.000577 -1.122585 -0.201654 -0.662704  0.247859 -0.429991   

   Factor13  Factor14  Factor15  
8 -0.032267  0.513381  0.505265

In [166]:
predict_rating(783,77)

array([[-0.10767012]])

In [167]:
predict_rating(5338,197)

array([[-0.23537891]])

In [182]:
predictions = []


for i in range(movie_df.shape[0]):
    predictions.append(predict_rating(4529, movie_df["Movie ID"][i]))

In [183]:
predictions

[array([[-0.03817154]]),
 array([[0.86605188]]),
 array([[-0.28531615]]),
 array([[0.01681209]]),
 array([[-0.24951037]]),
 array([[-0.70293821]]),
 array([[0.14435809]]),
 array([[-0.23324978]]),
 array([[0.2532789]]),
 array([[-0.14657534]]),
 array([[0.14637359]]),
 array([[-0.21154872]]),
 array([[-0.51129629]]),
 array([[0.14925896]]),
 array([[-0.21562325]]),
 array([[-0.24613903]]),
 array([[-0.15867464]]),
 array([[-0.08505838]]),
 array([[-0.15388412]]),
 array([[0.23018246]]),
 array([[0.17117963]]),
 array([[0.81749928]]),
 array([[0.00348498]]),
 array([[-0.00781021]]),
 array([[-0.56463309]]),
 array([[0.09538923]]),
 array([[-0.26683215]]),
 array([[0.16339702]]),
 array([[-0.16587494]]),
 array([[-0.06665299]]),
 array([[0.72288237]]),
 array([[-0.11003274]]),
 array([[0.04711015]]),
 array([[0.06992804]]),
 array([[-0.05149887]]),
 array([[0.51101532]]),
 array([[-0.67458857]]),
 array([[-0.46042008]]),
 array([[-0.01780727]]),
 array([[0.08940155]]),
 array([[-0.133422

In [186]:
predictions.sort()
predictions

[array([[-0.70293821]]),
 array([[-0.67458857]]),
 array([[-0.58671184]]),
 array([[-0.57804794]]),
 array([[-0.56463309]]),
 array([[-0.51129629]]),
 array([[-0.50207583]]),
 array([[-0.49262639]]),
 array([[-0.46655797]]),
 array([[-0.46042008]]),
 array([[-0.3991357]]),
 array([[-0.36540618]]),
 array([[-0.3579198]]),
 array([[-0.35119276]]),
 array([[-0.31151049]]),
 array([[-0.29712715]]),
 array([[-0.29593403]]),
 array([[-0.28531615]]),
 array([[-0.28252866]]),
 array([[-0.26683215]]),
 array([[-0.24951037]]),
 array([[-0.24748822]]),
 array([[-0.24613903]]),
 array([[-0.23623489]]),
 array([[-0.23324978]]),
 array([[-0.21562325]]),
 array([[-0.21154872]]),
 array([[-0.19912041]]),
 array([[-0.18683396]]),
 array([[-0.16587494]]),
 array([[-0.16283686]]),
 array([[-0.15867464]]),
 array([[-0.15865614]]),
 array([[-0.15388412]]),
 array([[-0.15371165]]),
 array([[-0.14657534]]),
 array([[-0.13653755]]),
 array([[-0.13495371]]),
 array([[-0.13371585]]),
 array([[-0.13342208]]),
 a

In [187]:
predictions2 = []


for i in range(movie_df.shape[0]):
    predictions2.append(predict_rating(2067, movie_df["Movie ID"][i]))

In [188]:
predictions2

[array([[-0.2394966]]),
 array([[0.32174264]]),
 array([[0.82894191]]),
 array([[0.26738451]]),
 array([[-0.40686824]]),
 array([[0.42134683]]),
 array([[0.06406957]]),
 array([[-0.02893417]]),
 array([[0.30464449]]),
 array([[0.02579574]]),
 array([[0.81701559]]),
 array([[0.28244354]]),
 array([[0.16758162]]),
 array([[0.48749678]]),
 array([[-1.9595769]]),
 array([[-1.88286055]]),
 array([[-1.82570715]]),
 array([[-0.09329798]]),
 array([[-0.05643398]]),
 array([[-0.26007506]]),
 array([[-0.26427929]]),
 array([[0.61841788]]),
 array([[0.2220632]]),
 array([[0.01079245]]),
 array([[0.00125333]]),
 array([[-0.02729693]]),
 array([[0.66374945]]),
 array([[0.3912517]]),
 array([[-0.1145333]]),
 array([[0.09272307]]),
 array([[0.40609585]]),
 array([[0.42870992]]),
 array([[0.08378097]]),
 array([[0.74320472]]),
 array([[0.0106485]]),
 array([[0.12487033]]),
 array([[0.27846965]]),
 array([[-0.32630758]]),
 array([[0.41807446]]),
 array([[0.4815616]]),
 array([[0.29459056]]),
 array([[0

In [190]:
predictions2.sort()
predictions2

[array([[-2.00020586]]),
 array([[-1.9821242]]),
 array([[-1.9595769]]),
 array([[-1.88286055]]),
 array([[-1.82570715]]),
 array([[-0.96988652]]),
 array([[-0.79691831]]),
 array([[-0.66487773]]),
 array([[-0.61143953]]),
 array([[-0.5886196]]),
 array([[-0.45369898]]),
 array([[-0.40686824]]),
 array([[-0.32630758]]),
 array([[-0.31115794]]),
 array([[-0.3059813]]),
 array([[-0.28165654]]),
 array([[-0.26427929]]),
 array([[-0.26007506]]),
 array([[-0.2578275]]),
 array([[-0.2394966]]),
 array([[-0.20759136]]),
 array([[-0.20003468]]),
 array([[-0.19285395]]),
 array([[-0.15075633]]),
 array([[-0.12434544]]),
 array([[-0.1145333]]),
 array([[-0.09329798]]),
 array([[-0.08892178]]),
 array([[-0.07380891]]),
 array([[-0.07297216]]),
 array([[-0.05643398]]),
 array([[-0.05197178]]),
 array([[-0.04743785]]),
 array([[-0.04164365]]),
 array([[-0.02893417]]),
 array([[-0.02729693]]),
 array([[-0.02260344]]),
 array([[0.00125333]]),
 array([[0.0043286]]),
 array([[0.00470649]]),
 array([[0.