<a href="https://colab.research.google.com/github/golfn123/CE888Project/blob/main/labs/lab6/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np


In [40]:
df = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv',header= None)
df

0      1      2      3      4    ...    96     97     98     99     100
0       74  -7.82   8.79  -9.66  -8.16  ...  99.00  -5.63  99.00  99.00  99.00
1      100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
2       49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3       48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
4       91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60
...    ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
24978  100   0.44   7.43   9.08   2.33  ...   9.03   6.55   8.69   8.79   7.43
24979   91   9.13  -8.16   8.59   9.08  ...  -8.20  -7.23  -8.59   9.13   8.45
24980   39  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24981   37  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24982   72   2.43   2.67  -3.98   4.27  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 101 columns]

In [41]:
df.replace(99, np.NaN,inplace= True)
df

0     1     2     3     4     5    ...   95    96    97    98    99    100
0       74.0 -7.82  8.79 -9.66 -8.16 -7.52  ...   NaN   NaN -5.63   NaN   NaN   NaN
1      100.0  4.08 -0.29  6.36  4.37 -2.38  ... -0.19 -2.14  3.06  0.34 -4.32  1.07
2       49.0   NaN   NaN   NaN   NaN  9.03  ...   NaN   NaN   NaN   NaN   NaN   NaN
3       48.0   NaN  8.35   NaN   NaN  1.80  ...   NaN   NaN   NaN   NaN   NaN   NaN
4       91.0  8.50  4.61 -4.17 -5.39  1.36  ...  5.73  1.55  3.11  6.55  1.80  1.60
...      ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
24978  100.0  0.44  7.43  9.08  2.33  3.20  ...  8.45  9.03  6.55  8.69  8.79  7.43
24979   91.0  9.13 -8.16  8.59  9.08  0.87  ...  9.22 -8.20 -7.23 -8.59  9.13  8.45
24980   39.0   NaN   NaN   NaN   NaN -7.77  ...   NaN   NaN   NaN   NaN   NaN   NaN
24981   37.0   NaN   NaN   NaN   NaN -9.71  ...   NaN   NaN   NaN   NaN   NaN   NaN
24982   72.0  2.43  2.67 -3.98  4.27 -2.28  ...   NaN   NaN   NaN   NaN   NaN   NaN

[24983 rows x 101 columns]

In [42]:
df=df.drop([0],axis=1)
df

1     2     3     4     5     6    ...   95    96    97    98    99    100
0     -7.82  8.79 -9.66 -8.16 -7.52 -8.50  ...   NaN   NaN -5.63   NaN   NaN   NaN
1      4.08 -0.29  6.36  4.37 -2.38 -9.66  ... -0.19 -2.14  3.06  0.34 -4.32  1.07
2       NaN   NaN   NaN   NaN  9.03  9.27  ...   NaN   NaN   NaN   NaN   NaN   NaN
3       NaN  8.35   NaN   NaN  1.80  8.16  ...   NaN   NaN   NaN   NaN   NaN   NaN
4      8.50  4.61 -4.17 -5.39  1.36  1.60  ...  5.73  1.55  3.11  6.55  1.80  1.60
...     ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
24978  0.44  7.43  9.08  2.33  3.20  6.75  ...  8.45  9.03  6.55  8.69  8.79  7.43
24979  9.13 -8.16  8.59  9.08  0.87 -8.93  ...  9.22 -8.20 -7.23 -8.59  9.13  8.45
24980   NaN   NaN   NaN   NaN -7.77   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
24981   NaN   NaN   NaN   NaN -9.71   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
24982  2.43  2.67 -3.98  4.27 -2.28  7.33  ...   NaN   NaN   NaN   NaN   NaN   NaN

[24983 rows x 100 columns]

In [43]:
#find lowest rating jokes
for i in df.columns:
  print(np.sum(df[i]))

14882.039999999999
3790.6299999999997
5268.429999999999
-22617.77
10079.63
32576.150000000005
-10731.25
-15590.27
-8774.35
26446.21
39404.29
32497.43
-44038.55
31438.47
-42615.79
-77542.83
-27856.229999999996
-15864.25
3852.28
-23331.24
52225.090000000004
18618.03
2187.4500000000003
-26794.539999999997
7959.469999999999
30548.010000000002
79439.31
36436.73
74115.2
-7846.83
54217.15
78735.58
-22861.890000000003
18533.27
75014.45999999999
82696.56999999999
-23025.46
29726.339999999997
24634.14
22367.42
-6014.820000000001
48324.159999999996
-16195.15
-34164.06
23641.240000000005
35442.97
34685.61000000001
45221.68
69163.28
91524.5
-13822.38
-2670.94
73401.34000000001
67547.1
9976.56
43657.36
-31796.87
-59628.33
-10482.22
-5844.410000000001
60999.969999999994
74210.05
4980.47
-11539.289999999999
56227.01
63342.759999999995
-15111.64
65819.94
63771.57
8460.99
-5865.7
23969.979999999996
9326.75
-13610.630000000001
-2380.4
22327.62
6398.469999999999
15803.86
831.7900000000002
10125.6
16938.60

In [73]:
avg_rate= -77542.83/24983
print(avg_rate)

-3.1038238001841254


In [74]:
df.iloc[13201, 62]

6.26

In [46]:
arr= df.values
arr

array([[-7.82,  8.79, -9.66, ...,   nan,   nan,   nan],
       [ 4.08, -0.29,  6.36, ...,  0.34, -4.32,  1.07],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       ...,
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [ 2.43,  2.67, -3.98, ...,   nan,   nan,   nan]])

In [47]:

def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with NaN's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr != np.NaN)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

replace(arr)

(array([[-7.82,  8.79, -9.66, ...,   nan,   nan,   nan],
        [ 4.08, -0.29,  6.36, ...,  0.34, -4.32,  1.07],
        [  nan,   nan,   nan, ...,   nan,   nan,   nan],
        ...,
        [  nan,   nan,   nan, ..., 99.  ,   nan,   nan],
        [  nan,   nan,   nan, ...,   nan,   nan, 99.  ],
        [ 2.43,  2.67, -3.98, ...,   nan,   nan, 99.  ]]),
 (array([20000, 12955, 24286, ..., 14370, 20525,  8173]),
  array([67, 70, 73, ..., 29,  2, 57])))

In [49]:
#load movie dataset
movie_df= pd.read_excel('movies_latent_factors.xlsx')
movie_df

Movie ID  ...  Factor15
0         11  ... -0.248806
1         12  ...  1.274993
2         13  ... -0.419092
3         14  ... -0.681191
4         22  ... -2.292566
..       ...  ...       ...
95      9806  ...  1.017861
96     10020  ... -0.487076
97     36657  ...  0.067790
98     36658  ... -0.288130
99     36955  ... -0.022599

[100 rows x 17 columns]

In [75]:
movie_df.loc[movie_df['Movie ID'] == 9331]

Movie ID                            Title  ...  Factor14  Factor15
92      9331  Clear and Present Danger (1994)  ... -0.207799  0.290987

[1 rows x 17 columns]

In [63]:
movie_df.loc[movie_df['Movie ID'] == 955]

Movie ID                          Title  ...  Factor14  Factor15
72       955  Mission: Impossible II (2000)  ...  1.547867 -0.997373

[1 rows x 17 columns]

In [76]:
movie_df['Factor14'].max()

2.2159327532871163

In [77]:
movie_df.loc[movie_df['Factor14']== 2.2159327532871163]

Movie ID           Title   Factor1  ...  Factor13  Factor14  Factor15
47       597  Titanic (1997)  1.567865  ...  0.370387  2.215933  0.456127

[1 rows x 17 columns]